var removeColors = require('./ansiStripper'),
    moment = require('moment'),
    fs = require('fs'),
    _s = require('underscore.string');

function Logger(options) {
  this._defaultPrefix = options.defaultPrefix || '';
  this._infoPrefix = options.infoPrefix || this._defaultPrefix;
  this._warnPrefix = options.warnPrefix || this._defaultPrefix;
  this._errPrefix = options.errPrefix || this._defaultPrefix;
  this._silent = options.silent || false; // silent saves log data on file system, instead of console.log'em.
  this.logFile = options.logFile || false;
}

Logger.prototype.info = function() {
  this._outputData(arguments, 'info');
};

Logger.prototype.error = function() {
  this._outputData(arguments, 'err');
};

Logger.prototype.warning = function() {
  this._outputData(arguments, 'warn');
};

Logger.prototype._outputData = function(args, type) {
  var datetime,
      prefix,
      data,
      forceSilent,
      sprintfVars;

  data = args[0];

  if (args[1] instanceof Array) {
    sprintfVars = args[1];

    data = _s.vsprintf(data, sprintfVars);

    if (typeof args[2] === 'boolean') {
      forceSilent = args[2];
    }
  } else if (typeof args[1] === 'boolean') {
    forceSilent = args[1];
  }

  if (this._silent || forceSilent) {
    if (!this.logFile) throw new Error('logFile option not provided.');
    if (!fs.existsSync(this.logFile)) throw new Error('logFile does not exists. Run `createLogs`.');

    datetime = moment().format('YYYY-MM-DD HH:mm:ss');
    data = removeColors(data);
    data = _s.sprintf('[ %s ] %s: %s \n', datetime, type.toUpperCase(), data);

    fs.appendFileSync(this.logFile, data);
  } else {
    prefix = this[_s.sprintf('_%sPrefix', type)];

    switch (type) {
      case 'info':
        console.log(prefix+data);
        break;
      case 'warn':
        console.warn(prefix+data);
        break;
      case 'err':
        console.error(prefix+data);
        break;
    }
  }
};

Logger.prototype.createLogs = function() {
  if (fs.existsSync(this.logFile)) return;

  var datetime = moment().format('YYYY-MM-DD HH:mm:ss');

  fs.writeFileSync(this.logFile, 'Generated by BrokenLinkChecker Logger utility - '+datetime+'\n\n');
  fs.chmodSync(this.logFile, 0777);
};

Logger.prototype.cleanLogs = function() {
  fs.unlinkSync(this.logFile);

  this.createLogs();
};

module.exports = Logger;